<?php //cookies section initially generated by claude
	// Initialize the VISITED_PAGES cookie as an empty array if it does not already exist.
	// json_encode() serializes the array into a string for cookie storage.
	// json_decode() with `true` deserializes it back into a PHP array when reading.
	if (!isset($_COOKIE['VISITED_PAGES'])) {
		$visited_pages = array();
		setcookie('VISITED_PAGES', json_encode($visited_pages), time() + (60 * 60 * 24 * 30), '/');
	}
 
	// Initialize COUNT_VISITS as an empty associative array if it does not already exist.
	// Each entry maps a product name (key) to its visit count (value).
	// e.g. {"Cheap Flip Phone": 1, "PVC Pipe 2.5in diameter 6in length": 3}
	if (!isset($_COOKIE['COUNT_VISITS'])) {
		$count_visits = array();
		setcookie('COUNT_VISITS', json_encode($count_visits), time() + (60 * 60 * 24 * 30), '/');
	}
?>

<!DOCTYPE html>
<!-- Products listing page; will eventually add support for product pages based on template -->
<html>
	<head>
		<meta charset="UTF-8">
		<title>Products/Services Page</title>
		<link href="./resources/css/index.css" type="text/css" rel="stylesheet">
	</head>
	
	<body>
		
		<div class = "menu">
			<?php require 'resources/php/nav_links.php'; ?>
		</div>
		
		<h1>Products/Services Page</h1>
		
		<p>
		This products and services page is currently under construction.
		Check back later for more products available for order.
		</p>
		
		<p align = "center">
			<a href="/productsCookiesVisited.php" class="button-class">Previously Visited Products</a>
			<a href="/productsCookiesVisitedCount.php" class="button-class">Most Visited Products</a>
		</p>
		
		<p>
		<a href="/productpages/productFlipPhone.php" class="button-class">Cheap Flip Phone</a><br>
		<a href="/productpages/productPVCPipe.php" class="button-class">PVC Pipe 2.5in diameter 6in length</a><br>
		<a href="/productpages/productCopper90Turn.php" class="button-class">Copper 90deg Corner Piece 1.0in diameter</a><br>
		<a href="/productpages/productPlumbingTape.php" class="button-class">Plumbing Tape (1/2in x 500in)</a><br>
		<a href="/productpages/productHeadphones.php" class="button-class">Simple Headphones</a><br>
		<a href="/productpages/productSmallLaptop.php" class="button-class">Small Laptop</a><br>
		<a href="/productpages/productPVC45Turn.php" class="button-class">PVC 45deg Elbow Piece 1.5in diameter</a><br>
		<a href="/productpages/productBrassValve.php" class="button-class">Brass Valve Straight 2.0in diameter 0.5in length</a><br>
		<a href="/productpages/productSpeakers.php" class="button-class">Wired Desk Speakers</a><br>
		<a href="/productpages/productRubberTube.php" class="button-class">Flexible Rubber Hose Coil 2.5in diameter 1ft length</a><br>

		</p>
		
		<div class = "footer">
			<?php include 'resources/php/footer.php'; ?>
		</div>
		
	</body>
</html>