<!DOCTYPE html>
<!-- Page that retrieves the COUNT_VISITS cookie to show the 5 most visited products -->
<html>
	<head>
		<meta charset="UTF-8">
		<title>Most Visited Products</title>
		<link href="./resources/css/index.css" type="text/css" rel="stylesheet">
	</head>
	
	<body>
		
		<div class = "menu">
			<?php require 'resources/php/nav_links.php'; ?>
		</div>
		
		<h1>Most Visited Products</h1>
		
		<p align = "center">
			<a href="/products.php" class="button-class">Back to Products/Services</a>
		</p>
		
		<p>
		Here is a list of the most visited products and their visit counts (maximum 5).
		</p>
		<?php //sorting initially generated by claude
			if (isset($_COOKIE['COUNT_VISITS'])) { // if cookie exists
				// Decode the JSON string from the cookie into a PHP associative array.
				// e.g. '{"Cheap Flip Phone":3,"PVC Pipe":1}' -> ["Cheap Flip Phone" => 3, "PVC Pipe" => 1]
				$sortedArray = json_decode($_COOKIE['COUNT_VISITS'], true);
 
				// arsort() sorts the array by value (visit count) in descending order
				// while keeping each product name (key) paired with its count (value).
				arsort($sortedArray);
 
				// Slice the array down to the top 5 highest values before printing.
				// true preserves the product name keys after slicing.
				$sortedArray = array_slice($sortedArray, 0, 5, true);
 
				// Print each product name and its visit count.
				foreach ($sortedArray as $name => $count) {
					print("$name: $count <br>");
				}
			} else { // if cookie does not exist
				print("Unable to retrieve most visited pages");
			}
		?>
		
		<div class = "footer">
			<?php include 'resources/php/footer.php'; ?>
		</div>
		
	</body>
</html>