<?php //template and cookie initially generated by claude
	// Product page template — require this file at the end of any product page.
	// The including file must define $NAME, $DESC, $PRICE, $IMG_SRC, and $IMG_ALT
	// before requiring this template.
	//
	// Cookie logic runs here so it is shared across all product pages.
	// $NAME must already be set by the including file before this template is required.

	// ---- Cookie: VISITED_PAGES ----
	// Read the existing VISITED_PAGES cookie, or start with an empty array if absent.
	$visited_pages = isset($_COOKIE['VISITED_PAGES'])
		? json_decode($_COOKIE['VISITED_PAGES'], true)
		: array();

	// Push the current product name into the visited pages array.
	array_push($visited_pages, $NAME);

	// If the array has grown beyond 5 elements, remove the oldest entry (index 0).
	if (count($visited_pages) > 5) {
		array_shift($visited_pages);
	}

	// Save the updated array back to the cookie (30-day expiry, site-wide path).
	setcookie('VISITED_PAGES', json_encode($visited_pages), time() + (60 * 60 * 24 * 30), '/');

	// ---- Cookie: COUNT_VISITS ----
	// Read the existing COUNT_VISITS cookie, or start with an empty associative array if absent.
	$count_visits = isset($_COOKIE['COUNT_VISITS'])
		? json_decode($_COOKIE['COUNT_VISITS'], true)
		: array();

	// If this product already has an entry, increment its count.
	// Otherwise, create a new entry for it starting at 1.
	if (isset($count_visits[$NAME])) {
		$count_visits[$NAME]++;
	} else {
		$count_visits[$NAME] = 1;
	}

	// Save the updated associative array back to the cookie.
	setcookie('COUNT_VISITS', json_encode($count_visits), time() + (60 * 60 * 24 * 30), '/');
?>

<!DOCTYPE html>
<!-- Product page template used for products; contains HTML formatting that is used -->
<html>
	<head>
		<meta charset="UTF-8">
		<title><?php print($NAME); ?></title>
		<link href="/resources/css/index.css" type="text/css" rel="stylesheet">
	</head>
	
	<body>
		
		<div class="menu">
			<?php require 'nav_links.php'; ?>
		</div>
		
		<p align="left">
			<a href="/products.php" class="button-class">Back to Products/Services</a>
		</p>
		
		<table>
			<tr>
				<td>
					<img src="<?php print($IMG_SRC); ?>" alt="<?php print($IMG_ALT); ?>">
				</td>
				<td>
					<h2><?php print($NAME); ?></h2>
					
					<?php
						for ($i = 0; $i < count($DESC); $i++)
							print("$DESC[$i] <br>");
					?>
					<br>
					<b>Cost: $<?php print($PRICE); ?></b>
					
				</td>
			</tr>
		</table>
		
		<div class="footer">
			<?php include 'footer.php'; ?>
		</div>
		
	</body>
</html>
