CREATE TABLE list_of_users (
	Fname VARCHAR(255) NOT NULL,
	Mname VARCHAR(255),
	Lname VARCHAR(255) NOT NULL,
	Email VARCHAR(255) NOT NULL,
	HomeAddress VARCHAR(255) NOT NULL,
	HomePhone VARCHAR(10),
	CellPhone VARCHAR(10),
	UserID VARCHAR(255) PRIMARY KEY
);