<?php //cookie and template usage initially generated by claude
	// ---- Product details ----
	$NAME = "Simple Headphones";
	$DESC = array(
		"A pair of slightly comfortable headphones you can wear.",
		"This is helpful if you want to listen to your music or protect your hearing while working on your projects."
	);
	$PRICE = 22.00;
	$DATE  = time();
 
	// Image variables used by product_template.php
	$IMG_SRC = "https://media.istockphoto.com/id/1412240771/photo/headphones-on-white-background.jpg";
	$IMG_ALT = "headphones";
?>
 
<?php require '../resources/php/product_template.php'; ?>
 