<?php //cookie and template usage initially generated by claude
	// ---- Product details ----
	$NAME = "Brass Valve Straight 2.0in diameter 0.5in length";
	$DESC = array(
		"A small brass valve to use to open and close fluid flow in your plumbing projects."
	);
	$PRICE = 3.50;
	$DATE  = time();
 
	// Image variables used by product_template.php
	$IMG_SRC = "https://www.shutterstock.com/image-photo/detailed-close-image-showcasing-brass-260nw-2638136665.jpg";
	$IMG_ALT = "brass valve";
?>
 
<?php require '../resources/php/product_template.php'; ?>
 