<?php //cookie and template usage initially generated by claude
	// ---- Product details ----
	$NAME = "Plumbing Tape (1/2in x 500in)";
	$DESC = array(
		"Plumbing tape that can be used to seal your pipes from possible leaks."
	);
	$PRICE = 5.50;
	$DATE = time();
 
	// Image variables used by product_template.php
	$IMG_SRC = "https://thumbs.dreamstime.com/b/teflon-tape-isolate-white-32747352.jpg";
	$IMG_ALT = "plumbing tape";
	
?>
 
<?php require '../resources/php/product_template.php'; ?>

