<?php //cookie and template usage initially generated by claude
	// ---- Product details ----
	$NAME = "PVC Pipe 2.5in diameter 6in length";
	$DESC = array(
		"A straight PVC pipe piece that has a diameter of 2.5 inches and a length of 6 inches."
	);
	$PRICE = 1.50;
	$DATE = time();
 
	// Image variables used by product_template.php
	$IMG_SRC = "https://www.shutterstock.com/image-photo/pvc-pipe-isolated-on-white-260nw-2626557113.jpg";
	$IMG_ALT = "pvc pipe";
	
?>
 
<?php require '../resources/php/product_template.php'; ?>

