<?php //cookie and template usage initially generated by claude
	// ---- Product details ----
	$NAME = "Cheap Flip Phone";
	$DESC = array(
		"A slightly used flip phone that can easily fit into your pockets.",
		"Perfect if you want to have a cheap option to call someone while on the go! (SIM included)"
	);
	$PRICE = 15.75;
	$DATE  = time();
 
	// Image variables used by product_template.php
	$IMG_SRC = "https://media.istockphoto.com/id/92377019/photo/clamshell-cell-phone.jpg";
	$IMG_ALT = "cheap flip phone";
?>
 
<?php require '../resources/php/product_template.php'; ?>
 