<?php //cookie and template usage initially generated by claude
	// ---- Product details ----
	$NAME = "PVC 45deg Elbow Piece 1.5in diameter";
	$DESC = array(
		"A PVC elbow turn tube piece that turns 45 degress and has a 1.5 inch diameter."
	);
	$PRICE = 1.25;
	$DATE = time();
 
	// Image variables used by product_template.php
	$IMG_SRC = "https://thumbs.dreamstime.com/b/pvc-45-degree-elbow-fitting-17334256.jpg";
	$IMG_ALT = "pvc 45 degree elbow piece";
	
?>
 
<?php require '../resources/php/product_template.php'; ?>

