<?php //cookie and template usage initially generated by claude
	// ---- Product details ----
	$NAME = "Copper 90deg Corner Piece 1.0in diameter";
	$DESC = array(
		"A copper corner turn tube piece that turns 90 degress and has a 1 inch diameter."
	);
	$PRICE = 1.00;
	$DATE = time();
 
	// Image variables used by product_template.php
	$IMG_SRC = "https://thumbs.dreamstime.com/b/single-copper-pipe-fitting-17090320.jpg";
	$IMG_ALT = "copper 90 degree turn piece";
	
?>
 
<?php require '../resources/php/product_template.php'; ?>

