<?php //cookie and template usage initially generated by claude
	// ---- Product details ----
	$NAME = "Small Laptop (10in screen size)";
	$DESC = array(
		"A compact laptop that can be easily carried for portability.",
		"Comes with the option of Windows or other operating systems."
	);
	$PRICE = 124.99;
	$DATE = time();
 
	// Image variables used by product_template.php
	$IMG_SRC = "https://media.istockphoto.com/id/176771450/photo/small-laptop.jpg";
	$IMG_ALT = "small laptop";
	
?>
 
<?php require '../resources/php/product_template.php'; ?>

