<?php //cookie and template usage initially generated by claude
	// ---- Product details ----
	$NAME = "Flexible Rubber Hose Coil 2.5in diameter 1ft length";
	$DESC = array(
		"A rubber hose coil with a 2.5inch diameter wiht a length of 1 foot.",
		"This hose is flexible and can fit into the tightest of corners and gaps!"
	);
	$PRICE = 7.50;
	$DATE = time();
 
	// Image variables used by product_template.php
	$IMG_SRC = "https://www.shutterstock.com/image-photo/black-flexible-corrugated-tube-coiled-600nw-2673528497.jpg";
	$IMG_ALT = "rubber hose coil";
	
?>
 
<?php require '../resources/php/product_template.php'; ?>

