<?php //cookie and template usage initially generated by claude
	// ---- Product details ----
	$NAME = "Wired Desk Speakers";
	$DESC = array(
		"A pair of speakers to put on your desk for playing audio.",
		"These speakers plug into the aux cord of your electronics."
	);
	$PRICE = 15.99;
	$DATE = time();
 
	// Image variables used by product_template.php
	$IMG_SRC = "https://www.shutterstock.com/image-photo/computer-speakers-isolated-on-white-260nw-177285980.jpg";
	$IMG_ALT = "desk speaker pair";
	
?>
 
<?php require '../resources/php/product_template.php'; ?>

